From 7febe335ce37f4aa3a605d43f815426144480485 Mon Sep 17 00:00:00 2001
From: linqili <linqili2006@users.noreply.github.com>
Date: Fri, 5 Aug 2016 18:09:06 +0800
Subject: [PATCH] fix : start HostedEngine failed after adding two or more
 nodes to data center

Signed-off-by: linqili <linqili2006@users.noreply.github.com>
---
 vdsm/virt/vm.py | 12 +++++++++++-
 1 file changed, 11 insertions(+), 1 deletion(-)

diff --git a/vdsm/virt/vm.py b/vdsm/virt/vm.py
index 159fb5f..10943bb 100644
--- a/vdsm/virt/vm.py
+++ b/vdsm/virt/vm.py
@@ -343,9 +343,19 @@ class Vm(object):
         # fix bug 7431: host usb pass through failed
         # step 1 
         # add USB 1.x/2.0/3.0 controller
+        # check if usb controller has been added
+        usb_controller_index = 0
         usb_models = ['piix3-uhci', 'ehci', 'nec-xhci']
         ports = {}
-        for index in range(0, len(usb_models)):
+        for dev in self.conf['devices']:
+            if dev['type'] == hwclass.CONTROLLER and \
+                                dev['device'] == 'usb':
+                dev['index'] = str(usb_controller_index)
+                dev['model'] = usb_models[usb_controller_index]
+                ports[usb_models[usb_controller_index]] = 1
+                usb_controller_index += 1
+
+        for index in range(usb_controller_index, len(usb_models)):
             self.conf['devices'].append({
                 'type': hwclass.CONTROLLER, 'device': 'usb',
                 'index': str(index), 'model': usb_models[index]
-- 
2.7.4

